# services:
#   db:
#     profiles: ["localdb"]
#     image: postgres:16
#     container_name: swoop-db
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: deals_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       PGDATA: /var/lib/postgresql/data/pgdata
#     ports:
#       - "5432:5432"
#     volumes:
#       - swoop_pg_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d deals_db"]
#       interval: 10s
#       timeout: 5s
#       retries: 10
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_REMOTE_LOGIN_TOOLS: "${ENABLE_REMOTE_LOGIN_TOOLS:-true}"
    image: swoop:latest
    container_name: swoop-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # NODE_ENV: "${NODE_ENV:production}"
      NODE_ENV: "production"
      PORT: "${PORT:-4000}"
      DATABASE_URL: "${DATABASE_URL}"
      ALLOW_REMOTE_FACEBOOK_LOGIN: "${ALLOW_REMOTE_FACEBOOK_LOGIN:-false}"
      NO_VNC_PUBLIC_URL: "${NO_VNC_PUBLIC_URL:-http://localhost:6080/vnc.html}"
      NODE_OPTIONS: "${NODE_OPTIONS:---dns-result-order=ipv4first}"
    # ports:
    #   # - "4000:4000"
    #   - "8080:4000"
    #   - "6080:6080"
    # production
    ports:
      - "127.0.0.1:8080:4000"
      - "127.0.0.1:6080:6080"

      # - "80:4000" by nginex  proxy and certbot 
      # - "443:4000"
    volumes:
      - ./playwright:/app/playwright
      - ./data:/app/data
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync+restart
        - path: ./public
          target: /app/public
          action: sync+restart
        - path: ./scripts
          target: /app/scripts
          action: sync+restart
        - path: ./prisma
          target: /app/prisma
          action: sync+restart
        - path: ./prisma.config.ts
          target: /app/prisma.config.ts
          action: sync+restart
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./.env
          action: rebuild
        - path: ./Dockerfile
          action: rebuild



# volumes:
#   swoop_pg_data:
