# services:
#   db:
#     profiles: ["localdb"]
#     image: postgres:16
#     container_name: swoop-db
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: deals_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       PGDATA: /var/lib/postgresql/data/pgdata
#     ports:
#       - "5432:5432"
#     volumes:
#       - swoop_pg_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d deals_db"]
#       interval: 10s
#       timeout: 5s
#       retries: 10
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: swoop:latest
    container_name: swoop-app
    restart: unless-stopped
    environment:
      NODE_ENV: "${NODE_ENV:-production}"
      PORT: "4000"
      DATABASE_URL: "${DATABASE_URL}"
      SCRAPE_CRON: "${SCRAPE_CRON}"
      RUN_SCAN_ON_BOOT: "false"
      MAX_LISTINGS_PER_FILTER: "30"
      LISTING_RETENTION_HOURS: "24"
      NOTIFICATION_RETENTION_HOURS: "12"
      NOTIFICATION_DELAY_MS: "2500"
      PLAYWRIGHT_HEADLESS: "true"
      ALLOW_REMOTE_FACEBOOK_LOGIN: "true"
      NO_VNC_PUBLIC_URL: ${NO_VNC_PUBLIC_URL:-http://localhost:6080/vnc.html}
      PLAYWRIGHT_BASE_URL: "https://www.facebook.com/marketplace"
      PLAYWRIGHT_STORAGE_STATE_PATH: "/app/playwright/storageState.json"
      PLAYWRIGHT_EXECUTABLE_PATH: ""
      PLAYWRIGHT_BROWSER_ARGS: "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage"
      DISPLAY: ":99"
      XVFB_SCREEN: "1366x768x24"
      VNC_PORT: "5900"
      NOVNC_PORT: "6080"
      VNC_PASSWORD: "${VNC_PASSWORD}"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_SECURE: "true"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASS: "${SMTP_PASS}"
      ALERT_FROM: "${ALERT_FROM}"
      ALERT_TO: "${ALERT_TO}"
      APP_AUTH_SECRET: "${APP_AUTH_SECRET:-1231hi32123}"
      APP_LOGIN_USERNAME: "${APP_LOGIN_USERNAME:-admin}"
      APP_LOGIN_PASSWORD: "${APP_LOGIN_PASSWORD:-admin123}"
      NODE_OPTIONS: "--dns-result-order=ipv4first"
    # ports:
    #   # - "4000:4000"
    #   - "8080:4000"
    #   - "6080:6080"
    # production
    ports:
      - "127.0.0.1:8080:4000"
      - "127.0.0.1:6080:6080"

      # - "80:4000" by nginex  proxy and certbot 
      # - "443:4000"
    volumes:
      - ./playwright:/app/playwright
      - ./data:/app/data

# volumes:
#   swoop_pg_data:
